### PR TITLE
Skip BLE scan if no device is configured

### PR DESCRIPTION
**Pull request by markhaehnel**
Don't initiate scans if no BLE devices are configured. (*null* in BLE section of the config)

### CODE REVIEW

**Comment by stfnhmplr** [comment]
That's a good idea. I just wonder if it might make more sense to perform the check already in the constructor. That would be a much shorter if statement. What do you think?

**Comment by markhaehnel** [comment]
You're right. I will rework my changes.

**Comment by markhaehnel** [comment]
It's in. You can look at it again! :)

**Comment by stfnhmplr** [comment]
Thanks!

**Pull request merged**
